AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  GlueDatabaseName:
    Type: String
    Description: 'The name of the Glue database'
    Default: 'codepipeline_event_logs'
  BufferingHintsSizeInMBs:
    Type: Number
    Default: 1
    Description: 'The size of the buffer, in MBs, that Kinesis Data Firehose uses for incoming data before delivering it to the S3 bucket'
  BufferingHintsIntervalInSeconds:
    Type: Number   
    Default: 60
    Description: 'The length of time, in seconds, that Kinesis Data Firehose buffers incoming data before delivering it to the S3 bucket'

Outputs:
  GlueDatabaseName:
    Value: !Ref GlueDatabaseName
    Description: 'The name of the Glue database'
  LogBucket:
    Value: !Ref LogBucket
    Description: 'The name of the S3 bucket holding the log files'
  DeliveryStreamLogGroup:
    Value: !Ref DeliveryStreamLogGroup
    Description: 'The name of the CloudWatch log group that contains logs for Kinesis Data Firehose errors'
  DeliveryStreamLogStream:
    Value: !Ref DeliveryStreamLogStream
    Description: 'The name of the CloudWatch log stream that contains logs for Kinesis Data Firehose errors'
  PipelineStateChangeTablename:
    Value: 'pipeline_execution_state_change'
    Description: 'The name of the Glue table for pipeline execution state change event logs'
  StageStateChangeTablename:
    Value: 'stage_execution_state_change'
    Description: 'The name of the Glue table for stage execution state change event logs'
  ActionStateChangeTablename:
    Value: 'action_execution_state_change'
    Description: 'The name of the Glue table for action execution state change event logs'

Resources:

  ### LOGS ###


  # S3 bucket containing log files
  LogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
          - Function:
              Fn::GetAtt:
              - CreatePartitionFunction
              - Arn
            Filter:
              S3Key:
                  Rules:
                  - Name: suffix
                    Value: .gz
                  - Name: prefix
                    Value: pipeline_execution_state_change
            Event: s3:ObjectCreated:*
          - Function:
              Fn::GetAtt:
              - CreatePartitionFunction
              - Arn
            Filter:
              S3Key:
                  Rules:
                  - Name: suffix
                    Value: .gz
                  - Name: prefix
                    Value: stage_execution_state_change
            Event: s3:ObjectCreated:*
          - Function:
              Fn::GetAtt:
              - CreatePartitionFunction
              - Arn
            Filter:
              S3Key:
                  Rules:
                  - Name: suffix
                    Value: .gz
                  - Name: prefix
                    Value: action_execution_state_change
            Event: s3:ObjectCreated:*

  # Glue database for codepipeline event logs
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref GlueDatabaseName

  # Glue table for pipeline state change events
  PipelineStateChangeTable:
    Type: AWS::Glue::Table
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput: 
        Name: pipeline_execution_state_change
        PartitionKeys:
          - Type: date
            Name: date
          - Type: string
            Name: hour
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            Location: !Sub 's3://${LogBucket}/pipeline_execution_state_change/'
            StoredAsSubDirectories: false
            SerdeInfo:
                SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
                Parameters:
                    serialization.format: '1'
            Columns:
                - 
                  Name: timestamp
                  Type: string
                - 
                  Name: eventVersion
                  Type: string
                - 
                  Name: pipelineArn
                  Type: string
                - 
                  Name: pipeline
                  Type: string
                - 
                  Name: version
                  Type: string
                - 
                  Name: state
                  Type: string
                - 
                  Name: executionId
                  Type: string

  # Glue table for stage state change events
  StageStateChangeTable:
    Type: AWS::Glue::Table
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput: 
        Name: stage_execution_state_change
        PartitionKeys:
          - Type: date
            Name: date
          - Type: string
            Name: hour
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            Location: !Sub 's3://${LogBucket}/stage_execution_state_change/'
            StoredAsSubDirectories: false
            SerdeInfo:
                SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
                Parameters:
                    serialization.format: '1'
            Columns:
                - 
                  Name: timestamp
                  Type: string
                - 
                  Name: eventVersion
                  Type: string
                - 
                  Name: pipelineArn
                  Type: string
                - 
                  Name: pipeline
                  Type: string
                - 
                  Name: version
                  Type: string
                - 
                  Name: state
                  Type: string
                - 
                  Name: stage
                  Type: string
                - 
                  Name: executionId
                  Type: string

  # Glue table for action state change events
  ActionStateChangeTable:
    Type: AWS::Glue::Table
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput: 
        Name: action_execution_state_change
        PartitionKeys:
          - Type: date
            Name: date
          - Type: string
            Name: hour
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            Location: !Sub 's3://${LogBucket}/action_execution_state_change/'
            StoredAsSubDirectories: false
            SerdeInfo:
                SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
                Parameters:
                    serialization.format: '1'
            Columns:
                - 
                  Name: timestamp
                  Type: string
                - 
                  Name: eventVersion
                  Type: string
                - 
                  Name: pipelineArn
                  Type: string
                - 
                  Name: pipeline
                  Type: string
                - 
                  Name: version
                  Type: string
                - 
                  Name: state
                  Type: string
                - 
                  Name: stage
                  Type: string
                - 
                  Name: action
                  Type: string
                - 
                  Name: region
                  Type: string
                - 
                  Name: executionId
                  Type: string
                - 
                  Name: type
                  Type: struct<owner:string,category:string,provider:string,version:string>

  # Lambda function that attempts to create a Glue partition when a log file is put into the S3 bucket
  CreatePartitionFunction:
      Type: AWS::Serverless::Function
      Properties:
          Handler: index.handler
          Runtime: python3.8
          CodeUri: lambdas/create-partition
          Timeout : 20
          Environment:
            Variables:
                DATABASE_NAME: !Ref GlueDatabase
          Policies:
            -
              Statement:
                - Effect: Allow
                  Action:
                    - 'glue:BatchCreatePartition'
                    - 'glue:CreatePartition'
                  Resource: "*"
                        
  # Lambda function permission to allow S3 to invoke 'CreatePartitionFunction'
  CreatePartitionFunctionDumpEventPermission:
      Type: AWS::Lambda::Permission
      Properties:
          Action: lambda:InvokeFunction
          SourceAccount:
              Ref: AWS::AccountId
          FunctionName:
              Ref: CreatePartitionFunction
          Principal: s3.amazonaws.com

  
  ### LOG DELIVERY ###

  # Firehose delivery stream that aggregates pipeline state change events into log files 
  PipelineStateChangeDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties: 
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        RoleARN: !GetAtt DeliveryStreamRole.Arn
        BucketARN: !Sub 'arn:aws:s3:::${LogBucket}'
        Prefix: 'pipeline_execution_state_change/'
        ErrorOutputPrefix: 'error/pipeline_execution_state_change/!{firehose:error-output-type}/year=!{timestamp:YYYY}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/'
        BufferingHints:
            SizeInMBs: !Ref BufferingHintsSizeInMBs
            IntervalInSeconds: !Ref BufferingHintsIntervalInSeconds
        CompressionFormat: GZIP
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref DeliveryStreamLogGroup
          LogStreamName: !Ref DeliveryStreamLogStream
        ProcessingConfiguration:
          Enabled: true
          Processors:
            -
                Type: Lambda
                Parameters:
                  - 
                    ParameterName: LambdaArn
                    ParameterValue: !GetAtt FirehoseTransformFunction.Arn

  # Firehose delivery stream that aggregates stage state change events into log files 
  StageStateChangeDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties: 
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        RoleARN: !GetAtt DeliveryStreamRole.Arn
        BucketARN: !Sub 'arn:aws:s3:::${LogBucket}'
        Prefix: 'stage_execution_state_change/'
        ErrorOutputPrefix: 'error/stage_execution_state_change/!{firehose:error-output-type}/year=!{timestamp:YYYY}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/'
        BufferingHints:
            SizeInMBs: !Ref BufferingHintsSizeInMBs
            IntervalInSeconds: !Ref BufferingHintsIntervalInSeconds
        CompressionFormat: GZIP
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref DeliveryStreamLogGroup
          LogStreamName: !Ref DeliveryStreamLogStream
        ProcessingConfiguration:
          Enabled: true
          Processors:
            -
                Type: Lambda
                Parameters:
                  - 
                    ParameterName: LambdaArn
                    ParameterValue: !GetAtt FirehoseTransformFunction.Arn

  # Firehose delivery stream that aggregates action state change events into log files 
  ActionStateChangeDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties: 
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        RoleARN: !GetAtt DeliveryStreamRole.Arn
        BucketARN: !Sub 'arn:aws:s3:::${LogBucket}'
        Prefix: 'action_execution_state_change/'
        ErrorOutputPrefix: 'error/action_execution_state_change/!{firehose:error-output-type}/year=!{timestamp:YYYY}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/'
        BufferingHints:
            SizeInMBs: !Ref BufferingHintsSizeInMBs
            IntervalInSeconds: !Ref BufferingHintsIntervalInSeconds
        CompressionFormat: GZIP
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref DeliveryStreamLogGroup
          LogStreamName: !Ref DeliveryStreamLogStream
        ProcessingConfiguration:
          Enabled: true
          Processors:
            -
                Type: Lambda
                Parameters:
                  - 
                    ParameterName: LambdaArn
                    ParameterValue: !GetAtt FirehoseTransformFunction.Arn
                      
  # Lambda function that transforms codepipeline events to fit the schema of the Glue tables
  FirehoseTransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: lambdas/firehose-transform
      Timeout: 60

  # A CloudWatch log group to hold error logs for the Firehose delivery streams
  DeliveryStreamLogGroup:
    Type: 'AWS::Logs::LogGroup'

  # A CloudWatch log stream to hold error logs for the Firehose delivery streams
  DeliveryStreamLogStream:
    Type: 'AWS::Logs::LogStream'
    Properties:
      LogGroupName: !Ref DeliveryStreamLogGroup

  # An IAM role giving the Firehose delivery streams access to the S3 log bucket, the CloudWatch log group/stream, and the transformation Lambda function
  DeliveryStreamRole:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
                - Sid: ''
                  Effect: Allow
                  Principal:
                    Service: firehose.amazonaws.com
                  Action: 'sts:AssumeRole'
                  Condition:
                    StringEquals:
                        'sts:ExternalId': !Ref 'AWS::AccountId'
        Path: "/"
        Policies:
            - PolicyName: firehose_delivery_policy
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action:
                        - 's3:AbortMultipartUpload'
                        - 's3:GetBucketLocation'
                        - 's3:GetObject'
                        - 's3:ListBucket'
                        - 's3:ListBucketMultipartUploads'
                        - 's3:PutObject'
                      Resource:
                            - !Join 
                                - ''
                                - - 'arn:aws:s3:::'
                                  - !Ref LogBucket
                            - !Join 
                                - ''
                                - - 'arn:aws:s3:::'
                                  - !Ref LogBucket
                                  - '/*'
                    - Effect: Allow
                      Action:
                        - 'logs:PutLogEvents'
                      Resource:
                        - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${DeliveryStreamLogGroup}:log-stream:${DeliveryStreamLogStream}"
                    - Effect: Allow
                      Action:
                            - 'lambda:InvokeFunction'
                      Resource:
                            - !GetAtt FirehoseTransformFunction.Arn


  ### EVENTS ###

  # Event rule capturing pipeline execution state changes
  PipelineStateChangeEventRule: 
      Type: AWS::Events::Rule
      Properties: 
        EventPattern: 
          source:
            - 'aws.codepipeline'
          detail-type:
            - 'CodePipeline Pipeline Execution State Change'
        State: "ENABLED"
        Targets:
          - Arn: !GetAtt PipelineStateChangeDeliveryStream.Arn
            Id: pipeline-state-change
            RoleArn: !GetAtt EventsRole.Arn

  # Event rule capturing stage execution state changes
  StageStateChangeEventRule: 
      Type: AWS::Events::Rule
      Properties: 
        EventPattern: 
          source:
            - 'aws.codepipeline'
          detail-type:
            - 'CodePipeline Stage Execution State Change'
        State: "ENABLED"
        Targets:
          - Arn: !GetAtt StageStateChangeDeliveryStream.Arn
            Id: stage-state-change
            RoleArn: !GetAtt EventsRole.Arn

  # Event rule capturing action execution state changes
  ActionStateChangeEventRule: 
      Type: AWS::Events::Rule
      Properties: 
        EventPattern: 
          source:
            - 'aws.codepipeline'
          detail-type:
            - 'CodePipeline Action Execution State Change'
        State: "ENABLED"
        Targets:
          - Arn: !GetAtt ActionStateChangeDeliveryStream.Arn
            Id: action-state-change
            RoleArn: !GetAtt EventsRole.Arn

  # IAM role giving the event rules permission to put records in the Firehose delivery streams
  EventsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
              - Sid: ''
                Effect: Allow
                Principal:
                  Service: events.amazonaws.com
                Action: 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'firehose:PutRecord'
                  - 'firehose:PutRecordBatch'
                Resource: 
                  - !GetAtt PipelineStateChangeDeliveryStream.Arn
                  - !GetAtt StageStateChangeDeliveryStream.Arn
                  - !GetAtt ActionStateChangeDeliveryStream.Arn