AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  DatabaseName:
    Type: String

Outputs:
  LogBucket:
    Value: !Ref LogBucket

Resources:

  LogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
          - Function:
              Fn::GetAtt:
              - CreatePartitionFunction
              - Arn
            Filter:
              S3Key:
                  Rules:
                  - Name: suffix
                    Value: .gz
                  - Name: prefix
                    Value: pipeline_execution_state_change
            Event: s3:ObjectCreated:*
          - Function:
              Fn::GetAtt:
              - CreatePartitionFunction
              - Arn
            Filter:
              S3Key:
                  Rules:
                  - Name: suffix
                    Value: .gz
                  - Name: prefix
                    Value: stage_execution_state_change
            Event: s3:ObjectCreated:*
          - Function:
              Fn::GetAtt:
              - CreatePartitionFunction
              - Arn
            Filter:
              S3Key:
                  Rules:
                  - Name: suffix
                    Value: .gz
                  - Name: prefix
                    Value: action_execution_state_change
            Event: s3:ObjectCreated:*


  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName

  
  PipelineStateChangeTable:
    Type: AWS::Glue::Table
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput: 
        Name: pipeline_execution_state_change
        PartitionKeys:
          - Type: date
            Name: date
          - Type: string
            Name: hour
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            Location: !Sub 's3://${LogBucket}/pipeline_execution_state_change/'
            StoredAsSubDirectories: false
            SerdeInfo:
                SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
                Parameters:
                    serialization.format: '1'
            Columns:
                - 
                  Name: timestamp
                  Type: string
                - 
                  Name: eventVersion
                  Type: string
                - 
                  Name: pipelineArn
                  Type: string
                - 
                  Name: pipeline
                  Type: string
                - 
                  Name: version
                  Type: string
                - 
                  Name: state
                  Type: string
                - 
                  Name: executionId
                  Type: string


  StageStateChangeTable:
    Type: AWS::Glue::Table
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput: 
        Name: stage_execution_state_change
        PartitionKeys:
          - Type: date
            Name: date
          - Type: string
            Name: hour
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            Location: !Sub 's3://${LogBucket}/stage_execution_state_change/'
            StoredAsSubDirectories: false
            SerdeInfo:
                SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
                Parameters:
                    serialization.format: '1'
            Columns:
                - 
                  Name: timestamp
                  Type: string
                - 
                  Name: eventVersion
                  Type: string
                - 
                  Name: pipelineArn
                  Type: string
                - 
                  Name: pipeline
                  Type: string
                - 
                  Name: version
                  Type: string
                - 
                  Name: state
                  Type: string
                - 
                  Name: stage
                  Type: string
                - 
                  Name: executionId
                  Type: string


  ActionStateChangeTable:
    Type: AWS::Glue::Table
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput: 
        Name: action_execution_state_change
        PartitionKeys:
          - Type: date
            Name: date
          - Type: string
            Name: hour
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            Location: !Sub 's3://${LogBucket}/action_execution_state_change/'
            StoredAsSubDirectories: false
            SerdeInfo:
                SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
                Parameters:
                    serialization.format: '1'
            Columns:
                - 
                  Name: timestamp
                  Type: string
                - 
                  Name: eventVersion
                  Type: string
                - 
                  Name: pipelineArn
                  Type: string
                - 
                  Name: pipeline
                  Type: string
                - 
                  Name: version
                  Type: string
                - 
                  Name: state
                  Type: string
                - 
                  Name: stage
                  Type: string
                - 
                  Name: action
                  Type: string
                - 
                  Name: region
                  Type: string
                - 
                  Name: executionId
                  Type: string
                - 
                  Name: type
                  Type: struct<owner:string,category:string,provider:string,version:string>


  CreatePartitionFunction:
      Type: AWS::Serverless::Function
      Properties:
          Handler: index.handler
          Runtime: python3.8
          CodeUri: ../lambdas/create-partition
          Timeout : 20
          Environment:
            Variables:
                DATABASE_NAME: !Ref GlueDatabase
          Policies:
            -
              Statement:
                - Effect: Allow
                  Action:
                    - 'glue:BatchCreatePartition'
                    - 'glue:CreatePartition'
                  Resource: "*"
                        

  CreatePartitionFunctionDumpEventPermission:
      Type: AWS::Lambda::Permission
      Properties:
          Action: lambda:InvokeFunction
          SourceAccount:
              Ref: AWS::AccountId
          FunctionName:
              Ref: CreatePartitionFunction
          Principal: s3.amazonaws.com