AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  GlueDatabaseName:
    Type: String
    Description: 'The name of the Glue database'
    Default: 'codepipeline_event_logs'
  BufferingHintsSizeInMBs:
    Type: Number
    Default: 1
    Description: 'The size of the buffer, in MBs, that Kinesis Data Firehose uses for incoming data before delivering it to the S3 bucket'
  BufferingHintsIntervalInSeconds:
    Type: Number   
    Default: 60
    Description: 'The length of time, in seconds, that Kinesis Data Firehose buffers incoming data before delivering it to the S3 bucket'

Outputs:
  GlueDatabaseName:
    Value: !Ref GlueDatabaseName
    Description: 'The name of the Glue database'
  LogBucket:
    Value: !GetAtt LogStack.Outputs.LogBucket
    Description: 'The name of the S3 bucket holding the log files'
  DeliveryStreamLogGroup:
    Value: !GetAtt DeliveryStack.Outputs.DeliveryStreamLogGroup
    Description: 'The name of the CloudWatch log group that contains logs for Kinesis Data Firehose errors'
  DeliveryStreamLogStream:
    Value: !GetAtt DeliveryStack.Outputs.DeliveryStreamLogStream
    Description: 'The name of the CloudWatch log stream that contains logs for Kinesis Data Firehose errors'
  PipelineStateChangeTablename:
    Value: 'pipeline_execution_state_change'
    Description: 'The name of the Glue table for pipeline execution state change event logs'
  StageStateChangeTablename:
    Value: 'stage_execution_state_change'
    Description: 'The name of the Glue table for stage execution state change event logs'
  ActionStateChangeTablename:
    Value: 'action_execution_state_change'
    Description: 'The name of the Glue table for action execution state change event logs'

Resources:

  LogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: logs.yaml
      Parameters:
        DatabaseName: !Ref GlueDatabaseName

  DeliveryStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: delivery.yaml
      Parameters:
        LogBucket: !GetAtt LogStack.Outputs.LogBucket
        IntervalInSeconds: !Ref BufferingHintsIntervalInSeconds
        SizeInMBs: !Ref BufferingHintsSizeInMBs

  EventStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: events.yaml
      Parameters:
        PipelineStateChangeDeliveryStreamArn: !GetAtt DeliveryStack.Outputs.PipelineStateChangeDeliveryStreamArn
        StageStateChangeDeliveryStreamArn: !GetAtt DeliveryStack.Outputs.StageStateChangeDeliveryStreamArn
        ActionStateChangeDeliveryStreamArn: !GetAtt DeliveryStack.Outputs.ActionStateChangeDeliveryStreamArn