AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  GlueDatabaseName:
    Type: String
    Description: 'The name of the Glue database'
    Default: 'codepipeline-event-logs'
  EventBusName:
    Type: String
    Description: 'The name of the event bus'
    Default: 'codepipeline-events'
  BufferingHintsSizeInMBs:
    Type: Number
    Default: 1
  BufferingHintsIntervalInSeconds:
    Type: Number   
    Default: 60

Outputs:
  GlueDatabaseName:
    Value: !Ref GlueDatabaseName
  EventBusName:
    Value: !Ref EventBusName
  LogBucket:
    Value: !GetAtt LogStack.Outputs.LogBucket
  DeliveryStreamLogGroup:
    Value: !GetAtt DeliveryStack.Outputs.DeliveryStreamLogGroup
  DeliveryStreamLogStream:
    Value: !GetAtt DeliveryStack.Outputs.DeliveryStreamLogStream
  PipelineStateChangeTablename:
    Value: 'pipeline_execution_state_change'
  StageStateChangeTablename:
    Value: 'stage_execution_state_change'
  ActionStateChangeTablename:
    Value: 'action_execution_state_change'

Resources:

  LogStack:
    Type: AWS::CloudFormation::Template
    Properties:
      TemplateURL: logs.yaml
      Parameters:
        DatabaseName: !Ref GlueDatabaseName

  DeliveryStack:
    Type: AWS::CloudFormation::Template
    Properties:
      TemplateURL: delivery.yaml
      Parameters:
        LogBucket: !GetAtt LogStack.Outputs.LogBucket
        IntervalInSeconds: !Ref BufferingHintsIntervalInSeconds
        SizeInMBs: !Ref BufferingHintsSizeInMBs

  EventStack:
    Type: AWS::CloudFormation::Template
    Properties:
      TemplateURL: events.yaml
      Parameters:
        EventBusName: !Ref EventBusName
        PipelineStateChangeDeliveryStreamArn: !GetAtt DeliveryStack.Outputs.PipelineStateChangeDeliveryStreamArn
        StageStateChangeDeliveryStreamArn: !GetAtt DeliveryStack.Outputs.StageStateChangeDeliveryStreamArn
        ActionStateChangeDeliveryStreamArn: !GetAtt DeliveryStack.Outputs.ActionStateChangeDeliveryStreamArn